# Generated by Django 3.2.8 on 2021-10-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urteil',
            name='bandenmaessig',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='urteil',
            name='freiheitsstrafe_in_monaten',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='urteil',
            name='nebenverurteilungsscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='urteil',
            name='vorbestraft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='urteil',
            name='vorbestraft_einschlaegig',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='urteil',
            name='fall_nr',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='urteil',
            name='geschlecht',
            field=models.CharField(choices=[('0', 'männlich'), ('1', 'weiblich')], default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='urteil',
            name='verfahrensart',
            field=models.CharField(choices=[('0', 'ordentlich'), ('1', 'abgekürzt')], default='0', max_length=15),
        ),
    ]
