# Generated by Django 3.2.8 on 2022-01-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_urteil_hauptdelikt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urteil',
            name='fall_nr',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
