# Generated by Django 3.2.8 on 2022-01-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_urteil_fall_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='urteil',
            name='vollzug',
            field=models.CharField(choices=[('0', 'bedingt'), ('1', 'teilbedingt'), ('2', 'unbedingt')], default='0', max_length=20),
        ),
    ]
