# Generated by Django 3.2.8 on 2022-01-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_urteil_vollzug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urteil',
            options={'verbose_name_plural': 'Urteile'},
        ),
        migrations.AddField(
            model_name='urteil',
            name='url_link',
            field=models.URLField(blank=True),
        ),
    ]
