# Generated by Django 3.2.8 on 2022-10-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20220123_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urteil',
            name='bandenmaessig',
            field=models.BooleanField(default=False, help_text='Ob das Delikt, für welches die Einsatzsstrafe gebildet wurde, bandenmässig begangen wurde.'),
        ),
        migrations.AlterField(
            model_name='urteil',
            name='deliktssumme',
            field=models.IntegerField(help_text='Die mit dem Delikt, für welches die Einsatzsstrafe gebildet wurde, erzielte Deliktssumme. Subsidiär die gesamthaft, mit allen Straftaten, erzielte Deliktssumme.'),
        ),
        migrations.AlterField(
            model_name='urteil',
            name='fall_nr',
            field=models.CharField(help_text='Die Verfahrensnummer des Urteils.', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='urteil',
            name='freiheitsstrafe_in_monaten',
            field=models.IntegerField(default=12, help_text='Die Dauer der angesprochenen Freiheitsstrafe in Monaten.'),
        ),
        migrations.AlterField(
            model_name='urteil',
            name='gewerbsmaessig',
            field=models.BooleanField(default=False, help_text='Ob das Delikt, für welches die Einsatzsstrafe gebildet wurde, gewerbsmässig begangen wurde.'),
        ),
        migrations.AlterField(
            model_name='urteil',
            name='hauptdelikt',
            field=models.CharField(choices=[('Betrug', 'Betrug'), ('Veruntreuung', 'Veruntreuung'), ('ung. Geschäftsbesorgung', 'ung. Geschäftsbesorgung'), ('betr. Missbrauch DVA', 'betr. Missbrauch DVA'), ('Diebstahl', 'Diebstahl'), ('Sachbeschädigung', 'Sachbeschädigung')], default='Betrug', help_text='Die Deliktsart, für welches die Einsatzsstrafe gebildet wurde.', max_length=30),
        ),
        migrations.AlterField(
            model_name='urteil',
            name='mehrfach',
            field=models.BooleanField(default=False, help_text='Ob das Delikt, für welches die Einsatzsstrafe gebildet wurde, mehrfach begangen wurde.'),
        ),
        migrations.AlterField(
            model_name='urteil',
            name='nebenverurteilungsscore',
            field=models.IntegerField(default=0, help_text='Anzahl der Schuldsprüche, welche neben dem Delikt, für welches die Einsatzsstrafe gebildet wurde, ausgesprochen wurden. + 1 Punkt für jedes weitere Vergehen. + 2 Punkt für jedes weitere Verbrechen. + 1 Punkt bei mehrfacher Begehung.'),
        ),
        migrations.AlterField(
            model_name='urteil',
            name='url_link',
            field=models.URLField(blank=True, help_text='Der URL-Link zum PDF des Urteils.'),
        ),
        migrations.AlterField(
            model_name='urteil',
            name='vorbestraft',
            field=models.BooleanField(default=False, help_text='Ob die verurteilte Person vorbestraft ist.'),
        ),
        migrations.AlterField(
            model_name='urteil',
            name='vorbestraft_einschlaegig',
            field=models.BooleanField(default=False, help_text='Ob die verurteilte Person einschlägig vorbestraft ist.'),
        ),
    ]
