# Generated by Django 3.2.8 on 2023-02-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20221029_1724'),
        ('database', '0009_auto_20221108_1927'),
    ]

    operations = [
    ]
