# Generated by Django 3.2.8 on 2023-02-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_merge_0009_auto_20221029_1724_0009_auto_20221108_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='urteil',
            name='gericht',
            field=models.CharField(default='n/a', help_text='Das Gericht, welches das Urteil gefällt hat.', max_length=30),
        ),
        migrations.AddField(
            model_name='urteil',
            name='nationalitaet',
            field=models.CharField(choices=[('0', 'Schweizerin/Schweizer'), ('1', 'Ausländer/Ausländerin'), ('2', 'unbekannt')], default='2', max_length=2),
        ),
        migrations.AddField(
            model_name='urteil',
            name='urteilsdatum',
            field=models.DateField(blank=True, help_text='Das Datum, an welchem das Gericht das Urteil gefällt hat.', null=True),
        ),
        migrations.AlterField(
            model_name='urteil',
            name='geschlecht',
            field=models.CharField(choices=[('0', 'männlich'), ('1', 'weiblich')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='urteil',
            name='verfahrensart',
            field=models.CharField(choices=[('0', 'ordentlich'), ('1', 'abgekürzt')], default='0', max_length=2),
        ),
    ]
