# Generated by Django 3.2.8 on 2023-02-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20230225_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagrammSVG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.ImageField(upload_to='diagramme/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='kimodelpicklefile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kimodelpicklefile',
            name='file',
            field=models.FileField(upload_to='pickles/'),
        ),
    ]
