# Generated by Django 3.2.8 on 2023-02-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20230228_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='kimodelpicklefile',
            name='prognoseleistung_dict',
            field=models.JSONField(default={'empty': True}),
            preserve_default=False,
        ),
    ]
