# Generated by Django 3.2.8 on 2023-03-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_kimodelpicklefile_prognoseleistung_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='kimodelpicklefile',
            name='encoder',
            field=models.FileField(blank=True, upload_to='encoders/'),
        ),
    ]
