# Generated by Django 3.2.8 on 2023-04-20 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_diagrammsvg_lesehinweis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Betm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menge_in_g', models.IntegerField()),
                ('rein', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BetmArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Kanton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abk', models.CharField(default='ZH', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Rolle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='urteil',
            name='gewerbsmaessig',
            field=models.BooleanField(default=False, help_text='Ob das Delikt, für welches die Einsatzsstrafe gebildet wurde, gewerbsmässig bzw. (bei der Veruntreuung) qualifiziert begangen wurde.', verbose_name='gewerbsmässig/qualifizierte Begehungsweise'),
        ),
        migrations.AlterField(
            model_name='urteil',
            name='vorbestraft',
            field=models.BooleanField(default=False, help_text='Ob die verurteilte Person vorbestraft ist.', verbose_name='vorbestraft'),
        ),
        migrations.AlterField(
            model_name='urteil',
            name='vorbestraft_einschlaegig',
            field=models.BooleanField(default=False, help_text='Ob die verurteilte Person einschlägig vorbestraft ist.', verbose_name='einschlägig vorbestraft'),
        ),
        migrations.CreateModel(
            name='BetmUrteil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mengemaessig', models.BooleanField(default=True)),
                ('bandenmaessig', models.BooleanField(default=False)),
                ('gewerbsmaessig', models.BooleanField(default=False)),
                ('anstaltentreffen', models.BooleanField(default=False)),
                ('mehrfach', models.BooleanField(default=False)),
                ('beschaffungskriminalitaet', models.BooleanField(default=False)),
                ('freiheitsstrafe_in_monaten', models.IntegerField(default=12, help_text='Die Dauer der ausgesprochenen Sanktion in Monaten.')),
                ('deliktsdauer_in_monaten', models.IntegerField(blank=True, null=True)),
                ('gericht', models.CharField(default='n/a', help_text='Das Gericht, welches das Urteil gefällt hat.', max_length=30)),
                ('urteilsdatum', models.DateField(blank=True, help_text='Das Datum, an welchem das Gericht das Urteil gefällt hat.', null=True)),
                ('fall_nr', models.CharField(help_text='Die Verfahrensnummer des Urteils, dem die Informationen entnommen sind.', max_length=15, unique=True)),
                ('url_link', models.URLField(blank=True, help_text='Der URL-Link zum PDF des Urteils, dem die Informationen entnommen sind.')),
                ('verfahrensart', models.CharField(choices=[('0', 'ordentlich'), ('1', 'abgekürzt')], default='0', max_length=2)),
                ('geschlecht', models.CharField(choices=[('0', 'männlich'), ('1', 'weiblich')], default='0', max_length=2)),
                ('nationalitaet', models.CharField(choices=[('0', 'Schweizerin/Schweizer'), ('1', 'Ausländer/Ausländerin'), ('2', 'unbekannt')], default='2', max_length=2)),
                ('nebenverurteilungsscore', models.IntegerField(default=0, help_text='Anzahl der Schuldsprüche, welche neben dem Delikt, für welches die Einsatzsstrafe gebildet wurde, ausgesprochen wurden. + 1 Punkt für jedes weitere Vergehen. + 2 Punkt für jedes weitere Verbrechen. + 1 Punkt bei mehrfacher Begehung.')),
                ('vorbestraft', models.BooleanField(default=False, help_text='Ob die verurteilte Person vorbestraft ist.', verbose_name='vorbestraft')),
                ('vorbestraft_einschlaegig', models.BooleanField(default=False, help_text='Ob die verurteilte Person einschlägig vorbestraft ist.', verbose_name='einschlägig vorbestraft')),
                ('betm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.betm')),
                ('kanton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.kanton')),
                ('rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.rolle')),
            ],
        ),
        migrations.AddField(
            model_name='betm',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.betmart'),
        ),
    ]
