# Generated by Django 3.2.8 on 2023-04-20 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_auto_20230420_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='betmurteil',
            options={'ordering': ['urteilsdatum'], 'verbose_name_plural': 'Betäubungsmittel-Urteile'},
        ),
    ]
