# Generated by Django 3.2.8 on 2023-07-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_betmurteil_deliktsertrag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betmurteil',
            name='betm',
        ),
        migrations.AddField(
            model_name='betmurteil',
            name='betm',
            field=models.ManyToManyField(to='database.Betm'),
        ),
    ]
