# Generated by Django 3.2.23 on 2023-12-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_urteil_in_ki_modell'),
    ]

    operations = [
        migrations.AddField(
            model_name='urteil',
            name='anzahl_tagessaetze',
            field=models.IntegerField(default=0, help_text='Die Zahl der ausgesprochenen Tagessätze der Geldstrafe'),
        ),
        migrations.AddField(
            model_name='urteil',
            name='hauptsanktion',
            field=models.CharField(choices=[('0', 'Freiheitsstrafe'), ('1', 'Geldstrafe'), ('2', 'Busse')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='urteil',
            name='freiheitsstrafe_in_monaten',
            field=models.IntegerField(default=12, help_text='Die Dauer der ausgesprochenen Freiheitsstrafe in Monaten.'),
        ),
    ]
