# Generated by Django 5.0 on 2024-01-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0024_auto_20231212_0019"),
    ]

    operations = [
        migrations.AddField(
            model_name="betmurteil",
            name="anzahl_tagessaetze",
            field=models.IntegerField(
                default=0,
                help_text="Die Zahl der ausgesprochenen Tagessätze der Geldstrafe",
            ),
        ),
        migrations.AddField(
            model_name="betmurteil",
            name="hauptsanktion",
            field=models.CharField(
                choices=[("0", "Freiheitsstrafe"), ("1", "Geldstrafe"), ("2", "Busse")],
                default="0",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="betmurteil",
            name="gericht",
            field=models.CharField(
                default="n/a",
                help_text="Das Gericht, welches das Urteil gefällt hat.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="urteil",
            name="gericht",
            field=models.CharField(
                default="n/a",
                help_text="Das Gericht, welches das Urteil gefällt hat.",
                max_length=50,
            ),
        ),
    ]
