# Generated by Django 5.0 on 2024-02-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0025_betmurteil_anzahl_tagessaetze_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="betmurteil",
            name="mengemaessig",
        ),
        migrations.AddField(
            model_name="betmurteil",
            name="in_ki_modell",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="betmurteil",
            name="mengenmaessig",
            field=models.BooleanField(
                default=True, help_text="Verurteilung nach Art. 19 Abs. 2 lit. a BetmG"
            ),
        ),
        migrations.AlterField(
            model_name="betmurteil",
            name="anstaltentreffen",
            field=models.BooleanField(
                default=False,
                help_text="zur ganzen oder einen gewissen Menge Betm wurdenlediglich Anstalten getroffen",
            ),
        ),
        migrations.AlterField(
            model_name="betmurteil",
            name="bandenmaessig",
            field=models.BooleanField(
                default=False, help_text="Verurteilung nach Art. 19 Abs. 2 lit. b BetmG"
            ),
        ),
        migrations.AlterField(
            model_name="betmurteil",
            name="beschaffungskriminalitaet",
            field=models.BooleanField(
                default=False,
                help_text="Dem Täter wird in der Begründung ein Suchtdruck attestiert. Die Anwendung des Privilegierungsgrunds in Art. 19 Abs. 3 lit. b BetmG ist nicht erforderlich.",
            ),
        ),
        migrations.AlterField(
            model_name="betmurteil",
            name="gewerbsmaessig",
            field=models.BooleanField(
                default=False, help_text="Verurteilung nach Art. 19 Abs. 2 lit. c BetmG"
            ),
        ),
    ]
