# Generated by Django 5.0.2 on 2024-04-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0026_remove_betmurteil_mengemaessig_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kimodelpicklefile",
            name="name",
            field=models.CharField(max_length=80),
        ),
    ]
