# Generated by Django 5.0.2 on 2024-09-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0027_alter_kimodelpicklefile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="betmurteil",
            name="zusammenfassung",
            field=models.TextField(
                blank=True,
                help_text="Die Zusammenfassung der massgebenden Erwägungen für die Strafzumessung",
            ),
        ),
        migrations.AddField(
            model_name="urteil",
            name="zusammenfassung",
            field=models.TextField(
                blank=True,
                help_text="Die Zusammenfassung der massgebenden Erwägungen für die Strafzumessung",
            ),
        ),
    ]
