# Generated by Django 5.0.2 on 2025-03-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_betmurteil_zusammenfassung_urteil_zusammenfassung'),
    ]

    operations = [
        migrations.AddField(
            model_name='betmurteil',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='betmurteil',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='urteil',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='urteil',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
