# Generated by Django 5.0.2 on 2025-03-15 15:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_betmurteil_add_time_betmurteil_update_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Besonderheiten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hauptdelikt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HauptdeliktTatmittel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZusaetzlicheSexualdelikte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='betmurteil',
            name='vollzug',
            field=models.CharField(choices=[('0', 'bedingt'), ('1', 'teilbedingt'), ('2', 'unbedingt')], default='2', max_length=20),
        ),
        migrations.CreateModel(
            name='SexualdeliktUrteil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fall_nr', models.CharField(help_text='Die Verfahrensnummer des Urteils, dem die Informationen entnommen sind.', max_length=15, unique=True)),
                ('url_link', models.URLField(blank=True, help_text='Der URL-Link zum PDF des Urteils, dem die Informationen entnommen sind.')),
                ('gericht', models.CharField(default='n/a', help_text='Das Gericht, welches das Urteil gefällt hat.', max_length=50)),
                ('urteilsdatum', models.DateField(blank=True, help_text='Das Datum, an welchem das Gericht das Urteil gefällt hat.', null=True)),
                ('hauptdelikt_mehrfachbegehung', models.BooleanField(choices=[(True, 'Ja'), (False, 'Nein')], default=False, help_text='Verurteilung wegen mehrfacher Begehung des Hauptdelikts', verbose_name='Mehrfachbegehung des Hauptdelikts?')),
                ('hauptdelikt_taeter_opfer_beziehung', models.CharField(choices=[('Ehegatte/Partner', 'Ehegatte/Partner'), ('Elternteil/Kind', 'Elternteil/Kind'), ('entfernt verwandt', 'entfernt verwandt'), ('Bekannte', 'Bekannte'), ('Unbekannt', 'Unbekannt')], default='Bekannte', max_length=50, verbose_name='Täter-Opfer-Beziehung')),
                ('hauptdelikt_opferalter', models.CharField(choices=[('unter_6', 'Unter 6 Jahren'), ('unter_10', 'Unter 10 Jahren'), ('unter_14', 'Unter 14 Jahren'), ('unter_16', 'Unter 16 Jahren'), ('unter_18', 'Unter 18 Jahren'), ('erwachsen', 'Erwachsen')], default='erwachsen', help_text='Alter des (jüngsten) Opfers des Hauptdelikts in Jahren.', max_length=20, verbose_name='Opferalter')),
                ('hauptdelikt_opfer_vorerfahrung', models.CharField(choices=[('Ja', 'Ja'), ('Nein', 'Nein'), ('unbekannt', 'unbekannt')], default='unbekannt', help_text='Ob das Opfer im Tatzeitpunkt sexuelle Vorerfahrungen hatte', verbose_name='Sexuelle Vorerfahrung des Opfers?')),
                ('hautpdelikt_deliktsdauer_einfachbegehung', models.DurationField(blank=True, default=datetime.timedelta(seconds=1800), help_text='Die Deliktsdauer des Hauptdelikts in Minuten, soweit bekannt.', null=True, verbose_name='Deliktsdauer Hauptdelikt (min)')),
                ('hauptdelikt_mehrfachbegehung_anzahl', models.IntegerField(blank=True, help_text='Anzahl der Vollendungen des Hauptdelikts', null=True)),
                ('hauptdelikt_mehrfachbegehung_deliktsperiode', models.DurationField(blank=True, default=datetime.timedelta(days=345), help_text='Periode, in welcher das Hauptdelikt mehrfach begangen wurde in Tagen', null=True, verbose_name='Deliktsperiode Hauptdelikt')),
                ('deliktsscore_uebrige_delikte', models.IntegerField(blank=True, help_text='Anzahl der Schuldsprüche, welche neben den Sexualdelikten ausgesprochen wurden. + 1 Punkt für jedes weitere Vergehen. + 2 Punkt für jedes weitere Verbrechen. + 1 Punkt bei mehrfacher Begehung.', null=True)),
                ('gestaendnisbonus', models.BooleanField(choices=[(True, 'Ja'), (False, 'Nein')], default=False, help_text='Ob ein Strafrabatt für ein Geständnis erfolgt.')),
                ('verletzung_beschleunigung', models.BooleanField(choices=[(True, 'Ja'), (False, 'Nein')], default=False, help_text='Ob ein Strafrabatt für die Verletzung des Beschleunigungsgebots erfolgt.')),
                ('geschlecht', models.CharField(choices=[('0', 'männlich'), ('1', 'weiblich')], default='0', help_text='Geschlecht des Täters', max_length=2)),
                ('nationalitaet', models.CharField(choices=[('0', 'Schweizerin/Schweizer'), ('1', 'Ausländer/Ausländerin'), ('2', 'unbekannt')], default='2', help_text='Nationalität des Täters', max_length=2)),
                ('vorbestraft', models.BooleanField(choices=[(True, 'Ja'), (False, 'Nein')], default=False, help_text='Ob Vorstrafen bestehen', verbose_name='vorbestraft')),
                ('vorbestraft_einschlaegig', models.BooleanField(choices=[(True, 'Ja'), (False, 'Nein')], default=False, help_text='Ob einschlägige Vorverurteilungen bestehen', verbose_name='einschlägig vorbestraft')),
                ('bemerkungen', models.TextField(blank=True, help_text='Individuelle Besonderheiten des Falles')),
                ('zusammenfassung', models.TextField(blank=True, help_text='Die Zusammenfassung der massgebenden Erwägungen für die Strafzumessung')),
                ('hauptsanktion', models.CharField(choices=[('0', 'Freiheitsstrafe'), ('1', 'Geldstrafe'), ('2', 'Busse')], default='0', max_length=1)),
                ('freiheitsstrafe_in_monaten', models.IntegerField(default=12, help_text='Die Dauer der ausgesprochenen Sanktion in Monaten.')),
                ('anzahl_tagessaetze', models.IntegerField(default=0, help_text='Die Zahl der ausgesprochenen Tagessätze der Geldstrafe')),
                ('vollzug', models.CharField(choices=[('0', 'bedingt'), ('1', 'teilbedingt'), ('2', 'unbedingt')], default='2', max_length=20)),
                ('verfahrensart', models.CharField(choices=[('0', 'ordentlich'), ('1', 'abgekürzt')], default='0', max_length=2)),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('besonderheiten', models.ManyToManyField(related_name='besonderheiten', to='database.besonderheiten')),
                ('hauptdelikt', models.ForeignKey(help_text='Das Hauptdelikt, für welches die Einsatzstrafe gebildet wird.', on_delete=django.db.models.deletion.CASCADE, related_name='hauptdelikt', to='database.hauptdelikt')),
                ('hauptdelikt_tatmittel', models.ForeignKey(help_text='Das Tatmittel, mit welchem das Hauptdelikt begangen wurde', on_delete=django.db.models.deletion.CASCADE, related_name='hauptdelikt_tatmittel', to='database.hauptdelikttatmittel')),
                ('kanton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.kanton')),
                ('sexualdelikte_zusaetzliche', models.ManyToManyField(help_text='weitere Sexualdelikte im Urteilsspruch', related_name='sexualdelikte', to='database.zusaetzlichesexualdelikte')),
            ],
            options={
                'verbose_name_plural': 'Urteile',
                'ordering': ['add_time'],
            },
        ),
    ]
