# Generated by Django 5.0.2 on 2025-03-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_besonderheiten_hauptdelikt_hauptdelikttatmittel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='betmurteil',
            options={'ordering': ['urteilsdatum'], 'verbose_name_plural': 'Betäubungsmitteldelikt-Urteile'},
        ),
        migrations.AlterModelOptions(
            name='sexualdelikturteil',
            options={'ordering': ['add_time'], 'verbose_name_plural': 'Sexualdelikt-Urteile'},
        ),
        migrations.AlterModelOptions(
            name='urteil',
            options={'ordering': ['urteilsdatum'], 'verbose_name_plural': 'Vermögensdelikt-Urteile'},
        ),
        migrations.AlterField(
            model_name='besonderheiten',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='hauptdelikt',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hauptdelikttatmittel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sexualdelikturteil',
            name='hauptdelikt_taeter_opfer_beziehung',
            field=models.CharField(choices=[('Ehegatte/Partner', 'Ehegatte/Partner'), ('Elternteil/Kind', 'Elternteil/Kind'), ('entfernt verwandt', 'entfernt verwandt'), ('Bekannte', 'Bekannte'), ('Unbekannte', 'Unbekannte'), ('Beziehung unbekannt', 'Beziehung unbekannt')], default='Bekannte', max_length=50, verbose_name='Täter-Opfer-Beziehung'),
        ),
        migrations.AlterField(
            model_name='zusaetzlichesexualdelikte',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
