# Generated by Django 5.0.2 on 2025-03-16 21:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_rename_hauptdelikttatmittel_tatmittel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sexualdelikturteil',
            name='hauptdelikt',
            field=models.ForeignKey(help_text='Das Hauptdelikt, für welches die Einsatzstrafe gebildet wird.', on_delete=django.db.models.deletion.CASCADE, related_name='hauptdelikt', to='database.hauptdelikt', verbose_name='Hauptdelikt'),
        ),
        migrations.AlterField(
            model_name='sexualdelikturteil',
            name='hauptdelikt_mehrfachbegehung',
            field=models.BooleanField(choices=[(True, 'Ja'), (False, 'Nein')], default=False, help_text='Verurteilung wegen mehrfacher Begehung des Hauptdelikts', verbose_name='mehrfache Tatbegehung?'),
        ),
        migrations.AlterField(
            model_name='sexualdelikturteil',
            name='hauptdelikt_mehrfachbegehung_deliktsperiode',
            field=models.DurationField(blank=True, default=datetime.timedelta(days=345), help_text='Periode, in welcher das Hauptdelikt mehrfach begangen wurde, in Tagen', null=True, verbose_name='Deliktsperiode Hauptdelikt'),
        ),
        migrations.AlterField(
            model_name='sexualdelikturteil',
            name='hauptdelikt_taeter_opfer_beziehung',
            field=models.CharField(choices=[('Ehegatte/Partner', 'Ehegatte/Partner'), ('Elternteil/Kind', 'Elternteil/Kind'), ('entfernt verwandt', 'entfernt verwandt'), ('Bekannte', 'Bekannte'), ('Unbekannte', 'Unbekannte'), ('Beziehung unbekannt', 'Beziehung unbekannt')], default='Bekannte', help_text='Beziehung zwischen Täter und Opfer', max_length=50, verbose_name='Täter-Opfer-Beziehung'),
        ),
        migrations.AlterField(
            model_name='sexualdelikturteil',
            name='hauptdelikt_tatmittel',
            field=models.ForeignKey(help_text='Das Tatmittel, mit welchem das Hauptdelikt begangen wurde', on_delete=django.db.models.deletion.CASCADE, related_name='hauptdelikt_tatmittel', to='database.tatmittel', verbose_name='Tatmittel'),
        ),
    ]
