# Generated by Django 5.0.2 on 2025-03-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0033_alter_sexualdelikturteil_hauptdelikt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sexualdelikturteil',
            name='hauptdelikt_deliktsdauer_bekannt',
            field=models.BooleanField(choices=[(True, 'Ja'), (False, 'Nein')], default=False),
        ),
        migrations.AlterField(
            model_name='sexualdelikturteil',
            name='hauptdelikt_opferalter',
            field=models.CharField(choices=[('unter_6', 'Unter 6 Jahren'), ('unter_10', 'Unter 10 Jahren'), ('unter_14', 'Unter 14 Jahren'), ('unter_16', 'Unter 16 Jahren'), ('unter_18', 'Unter 18 Jahren'), ('erwachsen', 'Erwachsen'), ('nicht bekannt', 'nicht bekannt')], default='erwachsen', help_text='Alter des (jüngsten) Opfers des Hauptdelikts in Jahren.', max_length=20, verbose_name='Opferalter'),
        ),
    ]
