# Generated by Django 5.0.2 on 2025-03-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0035_alter_sexualdelikturteil_sexualdelikte_zusaetzliche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sexualdelikturteil',
            name='gestaendnisbonus',
        ),
        migrations.RemoveField(
            model_name='sexualdelikturteil',
            name='verletzung_beschleunigung',
        ),
        migrations.AlterField(
            model_name='sexualdelikturteil',
            name='bemerkungen',
            field=models.TextField(blank=True, help_text='Besondere Bemerkungen zum Fall'),
        ),
        migrations.AlterField(
            model_name='sexualdelikturteil',
            name='hauptdelikt_opferalter',
            field=models.CharField(choices=[('unter_6', 'Unter 6 Jahren'), ('unter_10', 'Unter 10 Jahren'), ('unter_14', 'Unter 14 Jahren'), ('unter_16', 'Unter 16 Jahren'), ('unter_18', 'Unter 18 Jahren'), ('erwachsen', 'Erwachsen'), ('nicht bekannt', 'nicht bekannt')], default='erwachsen', help_text='Alter des (jüngsten) Opfers des Hauptdelikts (erste Begehung) in Jahren.', max_length=20, verbose_name='Opferalter'),
        ),
        migrations.AlterField(
            model_name='sexualdelikturteil',
            name='hauptdelikt_taeter_opfer_beziehung',
            field=models.CharField(choices=[('Ehegatte/Partner', 'Ehegatte/Partner'), ('Elternteil/Kind', 'Elternteil/Kind'), ('entfernt verwandt', 'entfernt verwandt'), ('Bekannte', 'Bekannte'), ('flüchtig Bekannt', 'flüchtig Bekannt'), ('Unbekannte', 'Unbekannte'), ('Beziehung unbekannt', 'Beziehung unbekannt')], default='Bekannte', help_text="Beziehung zwischen Täter und Opfer. 'flüchtig bekannt' bedeutet, dass der Täter und das Opfer sich bspw. am selben Abend kennengelernt haben.", max_length=50, verbose_name='Täter-Opfer-Beziehung'),
        ),
    ]
