# Generated by Django 5.0.2 on 2025-03-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_remove_sexualdelikturteil_gestaendnisbonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sexualdelikturteil',
            name='besonderheiten',
            field=models.ManyToManyField(blank=True, related_name='besonderheiten', to='database.besonderheiten'),
        ),
    ]
