# Generated by Django 5.0.2 on 2026-07-13 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0037_alter_sexualdelikturteil_besonderheiten'),
    ]

    operations = [
        migrations.CreateModel(
            name='GewaltdeliktUrteil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fall_nr', models.CharField(help_text='Die Verfahrensnummer des Urteils, dem die Informationen entnommen sind.', max_length=15, unique=True)),
                ('url_link', models.URLField(blank=True, help_text='Der URL-Link zum PDF des Urteils, dem die Informationen entnommen sind.')),
                ('gericht', models.CharField(default='n/a', help_text='Das Gericht, welches das Urteil gefällt hat.', max_length=50)),
                ('urteilsdatum', models.DateField(blank=True, help_text='Das Datum, an welchem das Gericht das Urteil gefällt hat.', null=True)),
                ('geschlecht', models.CharField(choices=[('0', 'männlich'), ('1', 'weiblich')], default='0', help_text='Geschlecht des Täters', max_length=2)),
                ('nationalitaet', models.CharField(choices=[('0', 'Schweizerin/Schweizer'), ('1', 'Ausländer/Ausländerin'), ('2', 'unbekannt')], default='2', help_text='Nationalität des Täters', max_length=2)),
                ('vorbestraft', models.BooleanField(default=False, help_text='Ob die verurteilte Person vorbestraft ist.', verbose_name='vorbestraft')),
                ('vorbestraft_einschlaegig', models.BooleanField(default=False, help_text='Ob die verurteilte Person einschlägig (Gewaltdelikt) vorbestraft ist.', verbose_name='einschlägig vorbestraft')),
                ('hauptdelikt', models.CharField(choices=[('Mord', 'Mord (Art. 112 StGB)'), ('vorsätzliche Tötung', 'vorsätzliche Tötung (Art. 111 StGB)'), ('Totschlag', 'Totschlag (Art. 113 StGB)'), ('fahrlässige Tötung', 'fahrlässige Tötung (Art. 117 StGB)'), ('schwere Körperverletzung', 'schwere Körperverletzung (Art. 122 StGB)'), ('einfache Körperverletzung', 'einfache Körperverletzung (Art. 123 StGB)'), ('Tätlichkeiten', 'Tätlichkeiten (Art. 126 StGB)'), ('Gefährdung des Lebens', 'Gefährdung des Lebens (Art. 129 StGB)'), ('Angriff', 'Angriff (Art. 134 StGB)'), ('Raufhandel', 'Raufhandel (Art. 133 StGB)'), ('Raub', 'Raub (Art. 140 StGB)')], default='einfache Körperverletzung', help_text='Das Delikt, für welches die Einsatzstrafe gebildet wurde.', max_length=40)),
                ('versuch', models.BooleanField(default=False, help_text='Ob das Hauptdelikt beim Versuch geblieben ist (Art. 22 StGB) – insb. bei Tötungsdelikten häufig.', verbose_name='Versuch')),
                ('tatmittel', models.CharField(choices=[('unbekannt', 'unbekannt/keine Angabe'), ('körperliche Gewalt', 'körperliche Gewalt (Faustschläge/Tritte)'), ('Würgen', 'Würgen/Drosseln'), ('Messer/Stichwaffe', 'Messer/Stich-/Schnittwerkzeug (auch Glas/Flasche)'), ('Schusswaffe', 'Schusswaffe'), ('stumpfer Gegenstand', 'stumpfer/gefährlicher Gegenstand'), ('andere', 'andere/mehrere')], default='unbekannt', help_text="Das beim Hauptdelikt eingesetzte Tatmittel. 'Messer/Stich-/Schnittwerkzeug' umfasst auch improvisierte scharfe Gegenstände (z.B. abgebrochene Flasche). Bei abgekürztem Verfahren oft nicht dokumentiert → 'unbekannt'.", max_length=30)),
                ('vorsatzform', models.CharField(choices=[('unbekannt', 'unbekannt/keine Angabe'), ('eventualvorsatz', 'Eventualvorsatz'), ('direktvorsatz', 'direkter Vorsatz'), ('fahrlaessig', 'Fahrlässigkeit')], default='unbekannt', help_text='Subjektiver Tatbestand des Hauptdelikts: Eventualvorsatz vs. direkter Vorsatz (bzw. Fahrlässigkeit, z.B. Art. 117 StGB). Bei Tötungs-/Körperverletzungsdelikten stark strafzumessungsrelevant.', max_length=20, verbose_name='Vorsatzform')),
                ('waffe_gefaehrlicher_gegenstand', models.BooleanField(default=False, help_text='Begehung mit Waffe oder gefährlichem Gegenstand (z.B. Raub Art. 140 Ziff. 2 StGB, KV Art. 123 Ziff. 2 StGB).', verbose_name='Waffe/gefährlicher Gegenstand')),
                ('bandenmaessig', models.BooleanField(default=False, help_text='Bandenmässige Begehung (z.B. Raub Art. 140 Ziff. 3 Abs. 2 StGB).')),
                ('besondere_gefaehrlichkeit', models.BooleanField(default=False, help_text='Besondere Gefährlichkeit bzw. besonders skrupellose/grausame Begehung (z.B. Raub Art. 140 Ziff. 3 Abs. 3, Mord Art. 112 StGB).', verbose_name='besondere Gefährlichkeit/Grausamkeit')),
                ('lebensgefahr', models.BooleanField(default=False, help_text='Herbeiführung einer Lebensgefahr für das Opfer (z.B. Raub Art. 140 Ziff. 4 StGB, lebensgefährliche Körperverletzung).', verbose_name='Lebensgefahr')),
                ('mehrfach', models.BooleanField(default=False, help_text='Ob das Hauptdelikt mehrfach begangen wurde.')),
                ('opferzahl', models.IntegerField(default=1, help_text='Anzahl der vom Hauptdelikt betroffenen Opfer.')),
                ('taeter_opfer_beziehung', models.CharField(choices=[('unbekannt', 'Beziehung unbekannt'), ('Partner/Ex-Partner', 'Partner/Ex-Partner (häusliche Gewalt)'), ('Familie', 'Familienangehörige'), ('Bekannte', 'Bekannte'), ('flüchtig bekannt', 'flüchtig bekannt'), ('Unbekannte', 'Unbekannte (Opfer war Fremder)')], default='unbekannt', help_text="Beziehung zwischen Täter und (Haupt-)Opfer. 'Unbekannte' = das Opfer war eine dem Täter fremde Person; 'unbekannt' = Beziehung nicht dokumentiert.", max_length=30, verbose_name='Täter-Opfer-Beziehung')),
                ('verletzungsfolge', models.CharField(choices=[('unbekannt', 'unbekannt/keine Angabe'), ('keine', 'keine (z.B. reiner Raub/Versuch)'), ('Tätlichkeit', 'geringfügig (Tätlichkeit)'), ('leicht', 'leichte Verletzung'), ('erheblich', 'erhebliche Verletzung'), ('schwer', 'schwere/bleibende Verletzung'), ('lebensgefährlich', 'lebensgefährliche Verletzung'), ('Tod', 'Tod des Opfers')], default='unbekannt', help_text='Schwerste eingetretene Verletzungsfolge beim Opfer des Hauptdelikts.', max_length=20)),
                ('angegriffenes_koerperteil', models.CharField(choices=[('unbekannt', 'unbekannt/keine Angabe'), ('nicht betroffen', 'nicht betroffen (z.B. reiner Raub)'), ('Kopf/Hals', 'Kopf/Hals'), ('Rumpf', 'Rumpf (Brust/Bauch/Rücken)'), ('Extremitäten', 'Extremitäten (Arme/Beine)'), ('mehrere', 'mehrere/ganzer Körper')], default='unbekannt', help_text='Vom Angriff (haupt-)betroffene Körperregion des Opfers – relevant für die Gefährlichkeit bei KV/Tötungsdelikten.', max_length=20, verbose_name='angegriffenes Körperteil')),
                ('substanzeinfluss', models.CharField(choices=[('unbekannt', 'unbekannt/keine Angabe'), ('nein', 'kein Einfluss'), ('Alkohol', 'Alkohol'), ('Drogen', 'Drogen/Medikamente'), ('Alkohol+Drogen', 'Alkohol und Drogen')], default='unbekannt', help_text='Ob der Täter im Tatzeitpunkt unter Alkohol-/Drogeneinfluss stand (strafzumessungsrelevant, Art. 19/47 StGB).', max_length=20, verbose_name='Substanzeinfluss')),
                ('deliktssumme', models.IntegerField(blank=True, help_text='Beute-/Deliktsbetrag – nur bei Raub relevant, bei Tötung/KV leer lassen.', null=True)),
                ('deliktsscore_uebrige_delikte', models.IntegerField(default=0, help_text='Anzahl der Schuldsprüche, welche neben dem Hauptdelikt ausgesprochen wurden. + 1 Punkt für jedes weitere Vergehen. + 2 Punkt für jedes weitere Verbrechen. + 1 Punkt bei mehrfacher Begehung.')),
                ('hauptsanktion', models.CharField(choices=[('0', 'Freiheitsstrafe'), ('1', 'Geldstrafe'), ('2', 'Busse')], default='0', max_length=1)),
                ('freiheitsstrafe_in_monaten', models.IntegerField(default=12, help_text='Die Dauer der ausgesprochenen Sanktion in Monaten.')),
                ('anzahl_tagessaetze', models.IntegerField(default=0, help_text='Die Zahl der ausgesprochenen Tagessätze der Geldstrafe')),
                ('vollzug', models.CharField(choices=[('0', 'bedingt'), ('1', 'teilbedingt'), ('2', 'unbedingt')], default='2', max_length=20)),
                ('verfahrensart', models.CharField(choices=[('0', 'ordentlich'), ('1', 'abgekürzt')], default='0', max_length=2)),
                ('in_ki_modell', models.BooleanField(default=True)),
                ('zusammenfassung', models.TextField(blank=True, help_text='Die Zusammenfassung der massgebenden Erwägungen für die Strafzumessung')),
                ('bemerkungen', models.TextField(blank=True, help_text='Besondere Bemerkungen zum Fall')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('besonderheiten', models.ManyToManyField(blank=True, help_text='Strafzumessungsrelevante Besonderheiten (z.B. verminderte Schuldfähigkeit, Affekt/entschuldbare Gemütsbewegung, Notwehr(-exzess), Geständnis/Reue, Provokation durch das Opfer).', related_name='gewaltdelikte', to='database.besonderheiten')),
                ('kanton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.kanton')),
            ],
            options={
                'verbose_name_plural': 'Gewaltdelikt-Urteile',
                'ordering': ['urteilsdatum'],
            },
        ),
    ]
