# Generated by Django 5.0.2 on 2026-09-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0038_gewaltdelikturteil'),
    ]

    operations = [
        migrations.CreateModel(
            name='PraejudizensucheLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation_id', models.CharField(db_index=True, help_text='Client-seitig erzeugte UUID, gruppiert die Turns einer Konversation.', max_length=64)),
                ('turn_index', models.PositiveIntegerField(help_text='0-basierter Index dieser Nachricht innerhalb der Konversation.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_message', models.TextField()),
                ('assistant_reply', models.TextField(blank=True)),
                ('tool_calls', models.JSONField(blank=True, default=list, help_text='Liste von {name, input} der in diesem Turn aufgerufenen eigenen Tools (ohne volle Tool-Resultate).')),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('rate_limited', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Präjudizensuche-Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
