# Generated by Django 5.0.2 on 2026-09-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0040_gewaltdelikturteil_kurzsachverhalt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sexualdelikturteil',
            name='kurzsachverhalt',
            field=models.TextField(blank=True, default='', help_text='Kurze Zusammenfassung des Sachverhalts (wird beim Hovern in der Urteilsliste angezeigt)'),
        ),
    ]
