# Generated by Django 5.0.2 on 2026-09-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0041_sexualdelikturteil_kurzsachverhalt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gewaltdelikturteil',
            name='fall_nr',
            field=models.CharField(help_text='Die Verfahrensnummer des Urteils, dem die Informationen entnommen sind.', max_length=25, unique=True),
        ),
    ]
