# Generated by Django 5.0.2 on 2026-09-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0042_alter_gewaltdelikturteil_fall_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gewaltdelikturteil',
            name='hauptdelikt',
            field=models.CharField(choices=[('Mord', 'Mord (Art. 112 StGB)'), ('vorsätzliche Tötung', 'vorsätzliche Tötung (Art. 111 StGB)'), ('Totschlag', 'Totschlag (Art. 113 StGB)'), ('fahrlässige Tötung', 'fahrlässige Tötung (Art. 117 StGB)'), ('schwere Körperverletzung', 'schwere Körperverletzung (Art. 122 StGB)'), ('einfache Körperverletzung', 'einfache Körperverletzung (Art. 123 StGB)'), ('fahrlässige Körperverletzung', 'fahrlässige Körperverletzung (Art. 125 StGB)'), ('Tätlichkeiten', 'Tätlichkeiten (Art. 126 StGB)'), ('Gefährdung des Lebens', 'Gefährdung des Lebens (Art. 129 StGB)'), ('Angriff', 'Angriff (Art. 134 StGB)'), ('Raufhandel', 'Raufhandel (Art. 133 StGB)'), ('Raub', 'Raub (Art. 140 StGB)')], default='einfache Körperverletzung', help_text='Das Delikt, für welches die Einsatzstrafe gebildet wurde.', max_length=40),
        ),
        migrations.AlterField(
            model_name='gewaltdelikturteil',
            name='tatmittel',
            field=models.CharField(choices=[('unbekannt', 'unbekannt/keine Angabe'), ('körperliche Gewalt', 'körperliche Gewalt (Faustschläge/Tritte)'), ('Würgen', 'Würgen/Drosseln'), ('Messer/Stichwaffe', 'Messer/Stich-/Schnittwerkzeug (auch Glas/Flasche)'), ('Schusswaffe', 'Schusswaffe'), ('stumpfer Gegenstand', 'stumpfer/gefährlicher Gegenstand'), ('Fahrzeug/Motorfahrzeug', 'Fahrzeug/Motorfahrzeug'), ('andere', 'andere/mehrere')], default='unbekannt', help_text="Das beim Hauptdelikt eingesetzte Tatmittel. 'Messer/Stich-/Schnittwerkzeug' umfasst auch improvisierte scharfe Gegenstände (z.B. abgebrochene Flasche). Bei abgekürztem Verfahren oft nicht dokumentiert → 'unbekannt'.", max_length=30),
        ),
    ]
