# Generated by Django 5.0.2 on 2026-09-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0043_alter_gewaltdelikturteil_hauptdelikt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='betmurteil',
            name='bemerkungen',
            field=models.TextField(blank=True, help_text='Besondere Bemerkungen zum Fall'),
        ),
        migrations.AddField(
            model_name='betmurteil',
            name='besonderheiten',
            field=models.ManyToManyField(blank=True, help_text='Strafzumessungsrelevante Besonderheiten (z.B. Geständnis/Reue, verminderte Schuldfähigkeit, Verletzung des Beschleunigungsgebots, Strafempfindlichkeit).', related_name='betmdelikte', to='database.besonderheiten'),
        ),
        migrations.AddField(
            model_name='betmurteil',
            name='kurzsachverhalt',
            field=models.TextField(blank=True, default='', help_text='Kurze Zusammenfassung des Sachverhalts (wird beim Hovern in der Urteilsliste angezeigt)'),
        ),
    ]
