# Generated by Django 5.0.2 on 2026-09-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0044_betmurteil_bemerkungen_betmurteil_besonderheiten_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urteil',
            name='bemerkungen',
            field=models.TextField(blank=True, help_text='Besondere Bemerkungen zum Fall'),
        ),
        migrations.AddField(
            model_name='urteil',
            name='besonderheiten',
            field=models.ManyToManyField(blank=True, help_text='Strafzumessungsrelevante Besonderheiten (z.B. Geständnis/Reue, Versuch, Gehilfenschaft, verminderte Schuldfähigkeit).', related_name='vermoegensdelikte', to='database.besonderheiten'),
        ),
        migrations.AddField(
            model_name='urteil',
            name='kurzsachverhalt',
            field=models.TextField(blank=True, default='', help_text='Kurze Zusammenfassung des Sachverhalts (wird beim Hovern in der Urteilsliste angezeigt)'),
        ),
        migrations.AddField(
            model_name='urteil',
            name='private_geschaedigte',
            field=models.CharField(choices=[('ja', 'ja'), ('nein', 'nein'), ('unbekannt', 'unbekannt')], default='unbekannt', help_text="Ob durch das Hauptdelikt Privatpersonen in ihrem Vermögen geschädigt wurden. 'nein', wenn ausschliesslich der Staat oder juristische Personen geschädigt wurden.", max_length=10, verbose_name='private Geschädigte'),
        ),
    ]
